/**
 * User configuration types for WikiPortraits uploader
 * Supports both global and per-event-type settings
 */

export interface CategoryConfiguration {
  // Categories that should always be added to images
  defaultImageCategories: string[];

  // Parent/organizational categories that should NOT be on images
  excludeFromImages: string[];

  // Auto-add performer categories when tagging performers
  autoAddPerformerCategories: boolean;

  // Auto-add "Band at Event" category
  autoAddBandAtEventCategory: boolean;
}

export interface PermissionConfiguration {
  // Default permission template text
  defaultPermissionText: string;

  // Auto-enable personality rights for events with people
  autoEnablePersonalityRights: boolean;

  // Custom permission templates
  customPermissionTemplates: Array<{
    name: string;
    template: string;
  }>;
}

export interface WorkflowConfiguration {
  // Auto-fetch band members when selecting a band
  autoFetchBandMembers: boolean;

  // Default license for new uploads
  defaultLicense: string;

  // Default author (supports Wikidata link format)
  defaultAuthor: string;

  // Auto-generate filenames
  autoGenerateFilenames: boolean;

  // Auto-generate descriptions
  autoGenerateDescriptions: boolean;
}

export interface WikiPortraitsConfiguration {
  // Event type for category organization
  eventType: 'music events' | 'festivals' | 'concerts' | 'sports events';

  // Custom accent color for WikiPortraits template
  accentColor: string;

  // Additional branding
  additionalBranding?: {
    enabled: boolean;
    text: string;
    logoImage?: string;
    logoLink?: string;
  };

  // Use WikiPortraits_uploader vs direct WikiPortraits template
  useUploaderTemplate: boolean;
}

export interface DepictsConfiguration {
  // Auto-add depicts statements when publishing
  autoAddDepicts: boolean;

  // Always include band/organization in depicts
  alwaysDepictOrganization: boolean;

  // Always include tagged performers in depicts
  alwaysDepictPerformers: boolean;
}

export interface UserConfiguration {
  version: number; // For migration purposes
  lastModified: Date;

  // Global settings (apply to all events)
  global: {
    categories: CategoryConfiguration;
    permissions: PermissionConfiguration;
    workflow: WorkflowConfiguration;
    wikiportraits: WikiPortraitsConfiguration;
    depicts: DepictsConfiguration;
  };

  // Per-event-type overrides
  eventTypeOverrides: {
    [eventType: string]: {
      categories?: Partial<CategoryConfiguration>;
      permissions?: Partial<PermissionConfiguration>;
      workflow?: Partial<WorkflowConfiguration>;
      wikiportraits?: Partial<WikiPortraitsConfiguration>;
      depicts?: Partial<DepictsConfiguration>;
    };
  };
}

// Default configuration
export const DEFAULT_CONFIGURATION: UserConfiguration = {
  version: 1,
  lastModified: new Date(),

  global: {
    categories: {
      defaultImageCategories: [],
      excludeFromImages: [
        'WikiPortraits', // Parent category
        // Band parent categories will be auto-detected by pattern
      ],
      autoAddPerformerCategories: true,
      autoAddBandAtEventCategory: true
    },

    permissions: {
      defaultPermissionText: 'Permission granted by the performers via messenger communication. Available upon request.',
      autoEnablePersonalityRights: false,
      customPermissionTemplates: [
        {
          name: 'Messenger Permission',
          template: '{{Consent|Permission granted by the performers via messenger communication on [DATE]. Available upon request.}}'
        },
        {
          name: 'Email Permission',
          template: '{{Consent|Permission granted via email on [DATE]. Available upon request.}}'
        },
        {
          name: 'Public Performance',
          template: '{{Consent|Public performance by professional performers at a public event.}}'
        }
      ]
    },

    workflow: {
      autoFetchBandMembers: true,
      defaultLicense: 'CC-BY-SA-4.0',
      defaultAuthor: '',
      autoGenerateFilenames: true,
      autoGenerateDescriptions: true
    },

    wikiportraits: {
      eventType: 'music events',
      accentColor: '#4b8510',
      additionalBranding: {
        enabled: false,
        text: '',
        logoImage: undefined,
        logoLink: undefined
      },
      useUploaderTemplate: true
    },

    depicts: {
      autoAddDepicts: true,
      alwaysDepictOrganization: true,
      alwaysDepictPerformers: true
    }
  },

  eventTypeOverrides: {}
};

// Helper type for partial updates
export type ConfigurationUpdate = Partial<UserConfiguration>;
